/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DreamStarterCollabortor } from "./DreamStarterCollabortor";

export { DreamStarterCollabortor__factory } from "./factories/DreamStarterCollabortor__factory";
